/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreatePlaceRequest,
  HTTPValidationError,
  ListPlacesEndpointPlacesGetParams,
  ResponseModelListPlace,
  ResponseModelPlace,
} from ".././model";

/**
 * @summary Create Place Endpoint
 */
export type createPlaceEndpointPlacesPostResponse201 = {
  data: ResponseModelPlace;
  status: 201;
};

export type createPlaceEndpointPlacesPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createPlaceEndpointPlacesPostResponseSuccess =
  createPlaceEndpointPlacesPostResponse201 & {
    headers: Headers;
  };
export type createPlaceEndpointPlacesPostResponseError =
  createPlaceEndpointPlacesPostResponse422 & {
    headers: Headers;
  };

export type createPlaceEndpointPlacesPostResponse =
  | createPlaceEndpointPlacesPostResponseSuccess
  | createPlaceEndpointPlacesPostResponseError;

export const getCreatePlaceEndpointPlacesPostUrl = () => {
  return `https://lengin-earch-back.vercel.app/places`;
};

export const createPlaceEndpointPlacesPost = async (
  createPlaceRequest: CreatePlaceRequest,
  options?: RequestInit,
): Promise<createPlaceEndpointPlacesPostResponse> => {
  const res = await fetch(getCreatePlaceEndpointPlacesPostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createPlaceRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createPlaceEndpointPlacesPostResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createPlaceEndpointPlacesPostResponse;
};

export const getCreatePlaceEndpointPlacesPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPlaceEndpointPlacesPost>>,
    TError,
    { data: CreatePlaceRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPlaceEndpointPlacesPost>>,
  TError,
  { data: CreatePlaceRequest },
  TContext
> => {
  const mutationKey = ["createPlaceEndpointPlacesPost"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPlaceEndpointPlacesPost>>,
    { data: CreatePlaceRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createPlaceEndpointPlacesPost(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePlaceEndpointPlacesPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPlaceEndpointPlacesPost>>
>;
export type CreatePlaceEndpointPlacesPostMutationBody = CreatePlaceRequest;
export type CreatePlaceEndpointPlacesPostMutationError = HTTPValidationError;

/**
 * @summary Create Place Endpoint
 */
export const useCreatePlaceEndpointPlacesPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPlaceEndpointPlacesPost>>,
      TError,
      { data: CreatePlaceRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPlaceEndpointPlacesPost>>,
  TError,
  { data: CreatePlaceRequest },
  TContext
> => {
  const mutationOptions =
    getCreatePlaceEndpointPlacesPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List Places Endpoint
 */
export type listPlacesEndpointPlacesGetResponse200 = {
  data: ResponseModelListPlace;
  status: 200;
};

export type listPlacesEndpointPlacesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listPlacesEndpointPlacesGetResponseSuccess =
  listPlacesEndpointPlacesGetResponse200 & {
    headers: Headers;
  };
export type listPlacesEndpointPlacesGetResponseError =
  listPlacesEndpointPlacesGetResponse422 & {
    headers: Headers;
  };

export type listPlacesEndpointPlacesGetResponse =
  | listPlacesEndpointPlacesGetResponseSuccess
  | listPlacesEndpointPlacesGetResponseError;

export const getListPlacesEndpointPlacesGetUrl = (
  params: ListPlacesEndpointPlacesGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://lengin-earch-back.vercel.app/places?${stringifiedParams}`
    : `https://lengin-earch-back.vercel.app/places`;
};

export const listPlacesEndpointPlacesGet = async (
  params: ListPlacesEndpointPlacesGetParams,
  options?: RequestInit,
): Promise<listPlacesEndpointPlacesGetResponse> => {
  const res = await fetch(getListPlacesEndpointPlacesGetUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listPlacesEndpointPlacesGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listPlacesEndpointPlacesGetResponse;
};

export const getListPlacesEndpointPlacesGetQueryKey = (
  params?: ListPlacesEndpointPlacesGetParams,
) => {
  return [
    `https://lengin-earch-back.vercel.app/places`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListPlacesEndpointPlacesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
  TError = HTTPValidationError,
>(
  params: ListPlacesEndpointPlacesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListPlacesEndpointPlacesGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>
  > = ({ signal }) =>
    listPlacesEndpointPlacesGet(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPlacesEndpointPlacesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>
>;
export type ListPlacesEndpointPlacesGetQueryError = HTTPValidationError;

export function useListPlacesEndpointPlacesGet<
  TData = Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
  TError = HTTPValidationError,
>(
  params: ListPlacesEndpointPlacesGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
          TError,
          Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPlacesEndpointPlacesGet<
  TData = Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
  TError = HTTPValidationError,
>(
  params: ListPlacesEndpointPlacesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
          TError,
          Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPlacesEndpointPlacesGet<
  TData = Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
  TError = HTTPValidationError,
>(
  params: ListPlacesEndpointPlacesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Places Endpoint
 */

export function useListPlacesEndpointPlacesGet<
  TData = Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
  TError = HTTPValidationError,
>(
  params: ListPlacesEndpointPlacesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPlacesEndpointPlacesGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPlacesEndpointPlacesGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
