"""create_places

Revision ID: 9d61d34122db
Revises:
Create Date: 2025-11-26 19:16:37.545871

"""

from typing import Sequence, Union

import domain
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d61d34122db"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("location", domain.place.tables.GeographyPoint(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("places")
    # ### end Alembic commands ###
