/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { Greating } from ".././model";

/**
 * @summary Root
 */
export type rootHealthcheckGetResponse200 = {
  data: Greating;
  status: 200;
};

export type rootHealthcheckGetResponseSuccess =
  rootHealthcheckGetResponse200 & {
    headers: Headers;
  };
export type rootHealthcheckGetResponse = rootHealthcheckGetResponseSuccess;

export const getRootHealthcheckGetUrl = () => {
  return `https://lengin-earch-back.vercel.app/healthcheck`;
};

export const rootHealthcheckGet = async (
  options?: RequestInit,
): Promise<rootHealthcheckGetResponse> => {
  const res = await fetch(getRootHealthcheckGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rootHealthcheckGetResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as rootHealthcheckGetResponse;
};

export const getRootHealthcheckGetQueryKey = () => {
  return [`https://lengin-earch-back.vercel.app/healthcheck`] as const;
};

export const getRootHealthcheckGetQueryOptions = <
  TData = Awaited<ReturnType<typeof rootHealthcheckGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof rootHealthcheckGet>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRootHealthcheckGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof rootHealthcheckGet>>
  > = ({ signal }) => rootHealthcheckGet({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof rootHealthcheckGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RootHealthcheckGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof rootHealthcheckGet>>
>;
export type RootHealthcheckGetQueryError = unknown;

export function useRootHealthcheckGet<
  TData = Awaited<ReturnType<typeof rootHealthcheckGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rootHealthcheckGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootHealthcheckGet>>,
          TError,
          Awaited<ReturnType<typeof rootHealthcheckGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRootHealthcheckGet<
  TData = Awaited<ReturnType<typeof rootHealthcheckGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rootHealthcheckGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootHealthcheckGet>>,
          TError,
          Awaited<ReturnType<typeof rootHealthcheckGet>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRootHealthcheckGet<
  TData = Awaited<ReturnType<typeof rootHealthcheckGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rootHealthcheckGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Root
 */

export function useRootHealthcheckGet<
  TData = Awaited<ReturnType<typeof rootHealthcheckGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rootHealthcheckGet>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getRootHealthcheckGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
