/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LocationPayload } from "./locationPayload";

export interface CreatePlaceRequest {
  /**
   * @minLength 1
   * @maxLength 2048
   */
  description: string;
  location: LocationPayload;
}
