/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ListPlacesEndpointPlacesGetParams = {
  /**
   * Latitude in decimal degrees
   * @minimum -90
   * @maximum 90
   */
  lat: number;
  /**
   * Longitude in decimal degrees
   * @minimum -180
   * @maximum 180
   */
  lng: number;
  /**
   * Maximum number of places to return
   * @maximum 1000
   */
  limit: number;
  /**
   * Number of records to skip before returning data
   * @minimum 0
   */
  offset: number;
};
