/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface LocationPayload {
  /**
   * Latitude in decimal degrees
   * @minimum -90
   * @maximum 90
   */
  lat: number;
  /**
   * Longitude in decimal degrees
   * @minimum -180
   * @maximum 180
   */
  lng: number;
}
