/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface Place {
  id: number;
  description: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location: [number, number];
  created_at: string;
  updated_at: string;
}
