/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ResponseModelListPlaceStatus =
  (typeof ResponseModelListPlaceStatus)[keyof typeof ResponseModelListPlaceStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseModelListPlaceStatus = {
  success: "success",
  error: "error",
} as const;
