/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ResponseModelPlaceStatus } from "./responseModelPlaceStatus";
import type { ResponseModelPlacePayload } from "./responseModelPlacePayload";
import type { ResponseModelPlaceMessage } from "./responseModelPlaceMessage";

export interface ResponseModelPlace {
  status: ResponseModelPlaceStatus;
  payload?: ResponseModelPlacePayload;
  message?: ResponseModelPlaceMessage;
}
