/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ResponseModelPlaceStatus =
  (typeof ResponseModelPlaceStatus)[keyof typeof ResponseModelPlaceStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseModelPlaceStatus = {
  success: "success",
  error: "error",
} as const;
