/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ResponseModelListPlaceStatus } from "./responseModelListPlaceStatus";
import type { ResponseModelListPlacePayload } from "./responseModelListPlacePayload";
import type { ResponseModelListPlaceMessage } from "./responseModelListPlaceMessage";

export interface ResponseModelListPlace {
  status: ResponseModelListPlaceStatus;
  payload?: ResponseModelListPlacePayload;
  message?: ResponseModelListPlaceMessage;
}
